include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_typing_uninitialized_variables: false
    prefer_const_constructors_in_immutables: false
    prefer_const_constructors: false
